- name: install unzip
  package:
    name: unzip
    state: present

- name: install java
  package:
    name: default-jdk
    state: present

- name: install supervisord
  package:
    name: supervisor
    state: present

- name: make directory for skyfactory
  file:
    path: /opt/mc/
    state: directory

- name: download sky factory
  unarchive:
    src: http://ftb.cursecdn.com/FTB2/modpacks/FTBPresentsSkyfactory3/{{ skyfactory_version }}/FTBPresentsSkyfactory3Server.zip
    dest: /opt/mc/
    remote_src: yes

- name: make FTB installer executable
  file:
    path: /opt/mc/FTBInstall.sh
    mode: 755

- name: run FTB installer
  shell: /opt/mc/FTBInstall.sh
  args:
    creates: /opt/mc/minecraft_server.{{ mc_version }}.jar

- name: update eula
  template:
    src: ./templates/eula.txt
    dest: /opt/mc/eula.txt

- name: make minecraft user
  user:
    name: minecraft

- name: set owner of mc files to minecraft user
  file:
    path: /opt/mc
    owner: minecraft
    group: minecraft
    recurse: yes

- name: upload skyfactory supervisord config
  template:
    src: ../templates/skyfactory.conf
    dest: /etc/supervisor/conf.d/skyfactory.conf

# note, in order to write to stdin on minecraft write to proc
# ex echo stop > /proc/4536/fd/0
#                      ^ PID of process
# get pid: supervisorctl status skyfactory
- name: restart supervisord
  service:
    name: supervisor
    state: restarted
