---
- name: install PPAs
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - 'ppa:webupd8team/atom'
    - 'ppa:ansible/ansible'
  become: yes

- name: install neccesary packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - vim
  - atom
  - guake
  - fish
  - keepassx
  - openvpn
  - supervisor
  - default-jdk
  - python-pip
  - virtualenv
  - rkhunter
  - ppa-purge
  - touchegg
  - nmap

  # Berea VPN
  - openconnect
  - network-manager-openconnect-gnome
  become: yes

- name: setup git
  template:
    src: .gitconfig
    dest: "{{ ansible_user_dir }}/.gitconfig"

- name: configure ansible
  template:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
  become: yes

- name: remove amazon crap
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/share/applications/ubuntu-amazon-default.desktop
    - /usr/share/unity-webapps/userscripts/unity-webapps-amazon/Amazon.user.js
    - /usr/share/unity-webapps/userscripts/unity-webapps-amazon/manifest.json
  become: yes
