---
- set_fact:
    distro: zesty

# Don't use the packages in the repos because they suck
- name: install the virtualbox deb
  apt:
    deb: "http://download.virtualbox.org/virtualbox/5.2.0/virtualbox-5.2_5.2.0-118431~Ubuntu~{{ distro }}_amd64.deb"
  become: yes

- name: download vagrant deb
  get_url:
    url: https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.deb
    dest: "/home/{{ user }}/Downloads/vagrant.deb"
    validate_certs: no

- name: install vagrant deb
  apt:
    deb: "/home/{{ user }}/Downloads/vagrant.deb"
  become: yes
