---
- name: Ensure required variables are defined
  fail: msg="{{ item }} value missing and is required"
  when: "item is not defined"
  with_items:
    - client
    - pki_password
    - ovpn_data

# not idempotant :(
- name: revoke easy rsa certificate
  shell: |
    docker run \
    -e PKI_PASS='{{ pki_password }}' \
    -v {{ ovpn_data }}:/etc/openvpn \
    --rm kylemanna/openvpn \
    /etc/openvpn/with_yes.sh easyrsa revoke {{ client }}
  no_log: true

# - name: remove ovpn config and keys
#   file:
#     path: "{{ item }}"
#     state: absent
#   with_items:
#     - "{{ ovpn_data }}client_confs/{{ client }}.ovpn"
#     - "{{ ovpn_data }}pki/private/{{ client }}.key"
#     - "{{ ovpn_data }}pki/issued/{{ client }}.crt"
