---
- hosts: localhost
  vars:
    home: /home/david/
    user: david

  tasks:
  - name: install git
    package:
      name: git
      state: present

  - name: create code file
    file:
      path: "{{ home }}/code"
      mode: 0700
      owner: "{{ user }}"
      group: "{{ user }}"
      state: directory

  - name: download automation repo
    git:
      repo: git@github.com:newswangerd/automation.git
      dest: "{{ home }}/code/automation"
