---
- hosts: localhost
  vars:
    home: /home/david/
    user: david

  tasks:
  - name: install git
    package:
      name: git
      state: present
    become: yes

  - name: create code file
    file:
      path: "{{ home }}/code"
      mode: 0700
      owner: "{{ user }}"
      group: "{{ user }}"
      state: directory

  - name: download automation repo
    git:
      repo: https://github.com/newswangerd/automation.git
      dest: "{{ home }}/code/automation"

  - name: configure git repo to use ssh
    lineinfile:
      path: "{{ home }}/code/automation/.git/config"
      regexp: '^	url = https://github.com/newswangerd/automation.git'
      line: '	url = git@github.com:newswangerd/automation.git'
